default['mariadb']['cluster_nodes']        = ""
default['mariadb']['mysqladmin_bin']       = "/usr/bin/mysqladmin"
default['mariadb']['mysql_bin']            = "/usr/bin/mysql"
default['mariadb']['server_root_password'] = ""
default['mariadb']['cluster_name'] = "my_galera_cluster"